### ISSUE TITLE
Can't change driver letter in windows

### ISSUE THREAD

**Issue by willser** [Barugon/egui_file#1]
Hi.
It's seems can't change  driver letter in windows.

![image](https://user-images.githubusercontent.com/64425242/197350540-4f036550-a9f1-44c2-ba0f-3321d1f478d7.png)

Up button is disable when `path` is root of  driver.

**Comment by willser** [comment]
I think it is possible to add a judgment on whether it is Windows or not to this code, and if so, try to get all the driverr letters

https://github.com/Barugon/egui_file/blob/c97c2029305f699ba5caf3285149cfdd38fb77e7/src/lib.rs#L567-L578

**Comment by Barugon** [comment]
For now, I believe that you can change the drive letter in the path edit. I'll try out your idea in Wine when I get a bit of time.

**Comment by Barugon** [comment]
@willser, can you give the latest a try? It works for me under Wine but I just want to make sure.
