### ISSUE TITLE
Filter manually entered path

### ISSUE THREAD

**Issue by Fabus1184** [Barugon/egui_file#27]
Currently, the filter option applies only to the files being shown. It would be nice to also check a manually entered path to allow only matching paths to be selected.

One could use the same filter as for the files, or a new one specially for the manually entered path. Of course this can be quite confusing for a user if he can't press save or select or whatever with a manually entered path without any visible reason as to why, but I think this would be on the developer to make sure the user knows what he can enter.

**Comment by bircni** [comment]
@Fabus1184 could you open a PR for that?
